### ISSUE TITLE
teststrandbias.R column counting error

### ISSUE THREAD

**Issue by tbmorrison** [AstraZeneca-NGS/VarDict#100]
I'm using -p (pileup) option for VarDict and this can create a column with no entry (e.g., TYPE) and result in the reported error "Error: Incorrect input detected in teststrandbias.R".  

Line 8 of teststrandbias.R counts columns by searching for "\\t+" which can be safely switched to "\\t" to avoid miscounting the empty columns.

**Comment by PolinaBevad** [comment]
@tbmorrison, hello and thank you for finding this problem! 
I prepared PR # 103 to solve this problem.

**Comment by PolinaBevad** [comment]
@tbmorrison, this change was added to the master! Thank you!
