### ISSUE TITLE
Warning messages

### ISSUE THREAD

**Issue by inti** [AstraZeneca-NGS/VarDict#11]
Hi,
I am trying VarDict on some RNA-seq data, I am getting the following message

```
Use of uninitialized value in numeric lt (<) at /home/shared/app/bcbio/tool/bin/vardict line 1329.
```

Should I get concerned about this warning? what does it mean?

All the best and thanks in advance

**Comment by zhongwulai** [comment]
Hi inti,

Which RNA-seq aligner did you use?  And which commit of VarDict did you use?  There's no "<" in line 1329 in the latest commit.  I have heavily tested STAR and TopHat and they should be fine for the latest commit.

Thanks for using VarDict.

-Zhongwu

**Comment by inti** [comment]
Hi,
The aligner I used was HISAT and I am using the version of the 2014-12-15 which I installed using cloudbiolinux. I will update and try again.

Thanks!
Inti

**Comment by zhongwulai** [comment]
Hi Inti,

Haven't tried any HISAT alignment.  I found each aligner might give some odd CIGAR for some specific situations.  As VarDict's algorithm modifies CIGAR extensively for local realignment so if the problem persists, please send a trimmed BAM file for us to test.

-Zhongwu

**Comment by inti** [comment]
I does not seems to kill the job … so I am not sure how bad it is neither where it happens …

**Comment by PolinaBevad** [comment]
The issue will be closed because it is outdate.
