### ISSUE TITLE
meet this error **"Incorrect input detected in testsomatic.R"**,

### ISSUE THREAD

**Issue by wentgithub** [AstraZeneca-NGS/VarDict#123]
here is my code, thanks a lot

/data/ngs/softs/VarDict-master/vardict -G /data/ngs/database/GATK_Resource_Bundle/hg19/ucsc.hg19.fasta -f 0.01 -N NGS201911-1SZ -b "NGS201911-1SZ.tumor.sorted.dedup.recal.bam|NGS201911-1SZ.normal.sorted.dedup.recal.bam" -c 1 -S 2 -E 3 -g 4 SZ.bed|/data/ngs/softs/VarDict-master/testsomatic.R|/data/ngs/softs/VarDict-master/var2vcf_paired.pl -N "NGS201911-1SZ|NGS201911-1SZ_normal" -f 0.01

**Comment by PolinaBevad** [comment]
@wentgithub , hello!
Sorry that you have the issue!

Could you please check if you have any result after running first part of command, before testsomatic.R, i.e
`/data/ngs/softs/VarDict-master/vardict -G /data/ngs/database/GATK_Resource_Bundle/hg19/ucsc.hg19.fasta -f 0.01 -N NGS201911-1SZ -b "NGS201911-1SZ.tumor.sorted.dedup.recal.bam|NGS201911-1SZ.normal.sorted.dedup.recal.bam" -c 1 -S 2 -E 3 -g 4 SZ.bed > raw_vardict.var`
If there will be any result, can you share this file?
Also, please, check that your bam files and fasta are indexed.

**Comment by wentgithub** [comment]
![image](https://user-images.githubusercontent.com/48668142/63401158-fc1c3400-c408-11e9-8e9c-8db453f42096.png)
It does the index all the time, and I can not get any output except the raw_vardict.var file, thanks a lot

**Comment by wentgithub** [comment]
ok, I have tried this, a paired sample ,each 6G bam file. 
and my SZ.bed is about 1.7M, it has run for 10 hours, but still not ended, is there any argument to speedup? thanks a lot

**Comment by PolinaBevad** [comment]
Hi @wentgithub, 

It is strange, because this warning that you see in the file must be shown in the console (or stderr) by default. It appears from the samtools library that we use, so we didn't create these errors inside our code.
I think the easiest way will be to recreate index for BAM files, to avoid these errors in output (with `samtools index path_to.bam`).

We don't have any arguments to speedup the process in Perl version of VarDict, but Java version (https://github.com/AstraZeneca-NGS/VarDictJava) can be run with `-th` option were you can set needed number of  cores to process regions from BED file in parallel. It is much more faster, so please, try it!

**Comment by wentgithub** [comment]
thanks a lot, it finally ok. but i still have some questions want to ask for help.
Q1: You can see bed file need gene name, but I do not supply it , it is still ok.
another is  for the amplicon calling.
Q2  if my bed does not contain the primer sequence ,so my 
Region start position and Start position – VarDict starts outputting variants from this position
Region end position and End position – VarDict ends outputting variants from this position
should be same, am i right?

Q3: the score is just a fake column, so i can give any value? and the 4 column bed can lack gene name, can 8 column lack gene name?



![image](https://user-images.githubusercontent.com/48668142/63504059-497ccc00-c503-11e9-8446-83d868cbebc0.png)

**Comment by PolinaBevad** [comment]
Hi @wentgithub,
Sorry for the delay in answering, I was on vacation for the past 2 weeks.

Q1: Yes, you can completely omit Gene column in 4th column BED file or you can set it as `.`, for example, and everything will be ok.
Q2: Yes, you are right.
Q3: Yes, Score and Strands columns aren't used, so you can set them to any values. And the same is for Gene column, simply set it to any value like `.` and it will be ok. We use a combination of the chromosome, start and end columns when working in amplicon mode.

**Comment by wentgithub** [comment]
thanks a lot, you are always so nice, @PolinaBevad 
Q1  another question is vardict can not used for germline calling, am I right?

Q2: in tumor-only mode, vardict call too many variants, is there some method to filter, I have seen the article you suggested, but not help,

**Comment by PolinaBevad** [comment]
Hi @wentgithub,

Your amplicon BED file looks ok. 

I don't quite understand what you mean by "enlarging the region". Do you want to change only Region start position and end position (2 and 3 columns), but Start and End (7 and 8 columns, i.e. positions without primers) will stay the same? You can do it, but VarDict will output variants only in the range between 7 and 8 columns.

**Comment by wentgithub** [comment]
thanks a lot@PolinaBevad 
because this data I just know it is amplicon data, and just has fatsq, do not have a bed file, so I create the bed file according to the transcript this fastq may contains. and calculate teh start position and end position by enlarge 500bp start and end postion, I do not know wthether it is ok.

Q1: after doing that, I found that vardict lose many variants that this fastq should contains, so I do not know whether it is right to do like so?

Q2: I have another question, is vardict suitable for germline variant calling?

**Comment by PolinaBevad** [comment]
Hi @wentgithub,

Usually, amplicon BED files must be provided by the manufacturer (PCR amplicon vendor). 
First you can check if there is the coverage in regions from your bed file with `bedtools` or `samtools bedcov`. If there are a lot of regions with zero a small coverage, perhaps this is the reason: some regions of your data are not covered by BED. 

Also, you can try to create BED file with `bamToBed` and extract only unique regions from it. It will be difficult to determine the situation where amplicons overlapping in such case, but you will get only the covered regions.
