### ISSUE TITLE
I have true sets, which vardict call high FP in tumor-only

### ISSUE THREAD

**Issue by wentgithub** [AstraZeneca-NGS/VarDict#124]
thanks for making this software calling the complex variant, this super all others.

but I found another problem, for tumor-only, even for paired, has high FP.
these days I also test a paired standard sample.

you know like gatk, it can supply a germline resource to filter gemline vatrianrts, can vardict also use this?

**Comment by PolinaBevad** [comment]
Hi @wentgithub,

Sorry, but we don't have such functionality as you mention for GATK. 

For this tumor-only case you have to process VarDict VCF results in some downstream software or make a script to filter germline variants: if you have VCF file from germline DB (dbSNP, for example) then go through variants from tumor VCF and check if they are in dbSNP. 

VarDict is a very sensitive variant caller, but you can "tune" the parameters to decrease FP rate: filter low mapping quality reads by `-Q 10`, remove QCfail reads with `-F 0x700` and so on. It can be done simpler by using VarDict in bcbio pipeline (https://github.com/bcbio/bcbio-nextgen), all the tunings are already included there. Please, take a look at it!
