### ISSUE TITLE
is vardict fit for germline calling?

### ISSUE THREAD

**Issue by wentgithub** [AstraZeneca-NGS/VarDict#125]
I do not see vardict saying it support germline calling, but in this paper "Evaluating Variant Calling Tools for Non-Matched Next-Generation Sequencing Data", it use vardict for variant calling

**Comment by PolinaBevad** [comment]
Hi @wentgithub,

Can you clarify what exactly do you mean by germline calling? Do you want to get variants from normal sample and determine their genotypes?

In the simple mode (if you use only one sample) you will get all variants without classification, but  VarDict also determines genotypes (GT field), so you can filter heterozygous variants.
But in the paired mode (if you use normal and tumor samples), VarDict will determine which variant is germline, somatic or LOH, and here you can see the full classification of variants: https://github.com/AstraZeneca-NGS/VarDict/wiki/Variant-classification-in-paired-analysis

**Comment by wentgithub** [comment]
so for tumor-only mode, vardict is not fit for calling somatic variants?
and I input one sample, it give me gemline and somatic variants?
like gatk, it has separate tool for gemline and somatic calling, because it rely on different hypothesis

**Comment by PolinaBevad** [comment]
Yes, exactly. 
We can determine somatic variants only in paired mode. Otherwise you will get both types of variants.

**Comment by wentgithub** [comment]
thanks a lot.so when it give both types of variants,  there is no method to distinguish ffrom germline and soamtic, am I right

**Comment by PolinaBevad** [comment]
Yes, you are right. 

I know that some software (Octopus, Pisces and other) can find somatic variants in tumor-only mode, but most of them will have up to 80-90% FP variants. Here is some summary: https://www.biostars.org/p/207536/  and https://www.biostars.org/p/270440/

**Comment by wentgithub** [comment]
I tired to install Octopus many times, but falied, thanks for your suggestion.
I have another question, you know sequence error, how for low vaf variant, how do vardict distinguish    whether this is a true somatic variant or just sequence error, I am eager to find some refernce about about this, 

I tried to read this article http://bioinformatics.cvr.ac.uk/blog/a-simple-method-to-distinguish-low-frequency-variants-from-illumina-sequence-errors/, but I can not calculate this value, I do it in R,
dbinom(7,35000,0.00032/3), the result is 0.04795766, not **0.08476547** 


Using the [1 – Binom(M; AvP/3, C)] formula (where C = 35,000, AvP/3 = 0.00032/3, and M = 7) gives a P value of  **0.08476547** which is not below the 0.05 threshold and so is not a validated low frequency mutation.

**Comment by PolinaBevad** [comment]
Hi @wentgithub,

We compare variants from both samples to decide whether it is somatic or not.
For example, if the variant has one read support in tumor sample it will be considered as LikelySomatic, and not StrongSomatic. Also, it will be filtered out if it has bad frequency or mapping and base quality. 

I think that in the article they used the cumulative probability that P(X >= x) (not binomial probability X=x). I'm not sure if R has this functionality, but perhaps some libraries can calculate this.  Just look here: https://stattrek.com/online-calculator/binomial.aspx

**Comment by wentgithub** [comment]
@PolinaBevad , I also calculate that, also not right, thanks a lot

**Comment by PolinaBevad** [comment]
For P(X>=x) I have the same values as in article: 
<img width="400" alt="portfolio_view"  src="https://user-images.githubusercontent.com/32058078/64961715-c8fd8100-d89e-11e9-81f5-3e4955ef2df8.png">

And in R P(X>=x) will be something like `cumsum(dbinom(7:35000, 35000, 0.00032/3))`. I see that from the 5-th value it will be `0.08476547`

**Comment by wentgithub** [comment]
I am really appreciated with your kind and continous help, what is the application you are using, can you share with me, thanks a lot

**Comment by PolinaBevad** [comment]
If I understand correctly, `pbinom` will calculate cumulative probability but only for P(X<=x) hypothesis. 

For other hypothesizes, you have to indicate it directly, as in this R script, and you can use it even online. I prepared this part here: https://rextester.com/live/UWJ7370
The image that was above is from this site: https://stattrek.com/online-calculator/binomial.aspx

**Comment by wentgithub** [comment]
yes, it contains the equal. thanks a lot

**Comment by PolinaBevad** [comment]
Great, I'm glad it helped!

I'll close the issues that we discussed (#124 and #125 as well), but feel free to open a new one if you will have other questions!
Thank you!
