### ISSUE TITLE
p0.05 Label

### ISSUE THREAD

**Issue by mpschr** [AstraZeneca-NGS/VarDict#13]
Hi

Just a quick question about the p0.05 filter annotation. To what test is the value corresponding? What is being tested?

Best

**Comment by zhongwulai** [comment]
This should be for paired analysis.  It refers to the p-value from Fisher Exact test.  The test uses numbers of reads (alt and ref) in two samples.  If p0.05 is in filter column, it means the allele frequency difference for the variant between two samples is not significant (p-value > 0.05).  It can be changed with "-p" option in script var2vcf_paired.pl, which defaults to 0.05.  Keep in mind the test is for somatic, as well as LOH or variants with significant allele frequency shifts.
