### ISSUE TITLE
how can I select complex variant from the result of vardict

### ISSUE THREAD

**Issue by 2236529177** [AstraZeneca-NGS/VarDict#133]
thanks a lot. due to gatk can not call complex variant, vardict did it well, so how can I select the complex variant. like variants in egfr.

chr7	55242470	.	TAAGAGAAGCAACATCTCCGAAAGCC	CGAAAGG	310	PASS	STATUS=StrongSomatic;SAMPLE=NGS201911-1SZ;TYPE=Complex;DP=1886;VD=531;AF=0.2815;SHIFT3=0;MSI=2.000;MSILEN=1;SSF=0;SOR=Inf;LSEQ=TCCCGTCGCTATCAAGGAAT;RSEQ=AACAAGGAAATCCTCGATGT	GT:DP:VD:ALD:RD:AD:AF:BIAS:PMEAN:PSTD:QUAL:QSTD:SBF:ODDRATIO:MQ:SN:HIAF:ADJAF:NM	0/1:1886:531:240,291:695,645:1340,531:0.2815:2,2:26.7:1:34.3:1:0.01032:1.30629:60:1062:0.2846:0.1458:0.1	0/0:1947:0:0,0:984,961:1945,0:0:0:0:0:0:0:1:0:0:0:0:0:0

**Comment by PolinaBevad** [comment]
Hi, 
Do you mean you want to select only complex variants from the VCF file?

If so you can use grep, like this:
`vardict_output.vcf | grep TYPE=Complex > vardict_only_complex.vcf`
You have to copy the header of the initial VCF also if you want to use result file as VCF.

**Comment by 2236529177** [comment]
Thanks  a lot. you are really always so kind and helpful
