### ISSUE TITLE
Error: Incorrect input detected in teststrandbias.R

### ISSUE THREAD

**Issue by monashhf** [AstraZeneca-NGS/VarDict#141]
Hi I am pretty new to the bioinformatics realm and am trying to run vardict on single sample mode for a germline sample. Script is as follows:

ref="/home/hfettke/uc23/software/human_g1k_v37.fasta"
bed="/home/hfettke/uc23/software/cellfree.bed"
export PATH=/home/hfettke/uc23/software/VarDict-1.5.8/bin/:$PATH

module load R/3.5.1
AF_THR="0.01" # minimum allele frequency
VarDict -G ${ref} -f $AF_THR -N 130238-G -b 130238-G.bwa.sorted.bam -c 1 -S 2 -E 3 -g 4 ${bed} > 1.txt
cat 1.txt | teststrandbias.R | var2vcf_valid.pl -N 130238-G -E -f $AF_THR > "130238.germline.vardict.tsv"

Unfortunately I am getting 
Error: Incorrect input detected in teststrandbias.R
Execution halted

I can see that some people have had this same issue but haven't been able to fix my error with the suggestions made in previous posts. 
I have outputted the first part of the script to 1.txt as you can see to see if there is something funny with the data going into R. The output is 36 columns. 

Since I have very little experience with bioinformatics I am unsure of what to do next. Could someone please help?

**Comment by PolinaBevad** [comment]
Hi @monashhf,

Sorry that you have an issue!

Could you try 1.6.0 or 1.7.0 version? And if this won't help, could you please share the first line of 1.txt file so I can see what's happening?

**Comment by monashhf** [comment]
Hi Polina,

Thanks for your reply - I figured out the issue: I was loading the R module twice so it was throwing up an error!
