### ISSUE TITLE
Running on WGS samples

### ISSUE THREAD

**Issue by vymao** [AstraZeneca-NGS/VarDict#143]
Hi, 

I am interested in running VarDict on WGS samples. I tried running it without a BED file for b37 but I get no variants called (I only see a VCF header). When I tried running VarDict on targeted panel sequencing with a BED file, it worked fine. 

This was the command I used: 
```
AF_THR="0.01"

tumor_sample_name=$1
tumor_bam=$2
normal_sample_name=$3
normal_bam=$4

vardict -G /path/to/b37/human_g1k_v37_decoy.fasta -f $AF_THR -N ${tumor_sample_name}\
 -b "${tumor_bam}|${normal_bam}" | testsomatic.R | var2vcf_paired.pl -N\
 "${tumor_sample_name}|${normal_sample_name}" -f $AF_THR
```

Is a BED file necessary? If so, how can we get one for b37?

**Comment by PolinaBevad** [comment]
Hi Viktor, I answered to issue in VarDictJava repository, so I'll close this one!
