### ISSUE TITLE
Missing Mutations

### ISSUE THREAD

**Issue by qub-pete** [AstraZeneca-NGS/VarDict#146]
Hello,
We are validating a mutation calling pipeline using VarDict to accompany a custom designed targeted panel.  We have ran Horizon Cell Line Blends (Tru-Q1 through to Tru-Q4) in triplicate and these cell lines have been engineered to have mutations present at particular frequencies.  

We can show our sequencing data is in good agreement with the manufacturers list of mutations and VAFs except when it comes to BRAF.  Each of the cell lines contains two BRAF mutations and we always can report the V600E mutation @ 8%VAF (A>T @ chr7:140753336), which is present in all 4 cell line blends, but we have noticed using the VarDict pipeline, that other mutations in three of the blends which occur 4%VAF and at the same chromosomal coordinate (chr7:140753336) are never called .

We have been looking into this issue.  When we use Mutect2 or visualise BAM files (using different alignment method) on IGV we can see the presence of the mutation.  Also when we use a different targeted NGS panel which also covers BRAF we notice the same observation specifically when using the VarDict pipeline.

Would anyone have any suggestions why the VarDict pipeline would not report a second mutation at the same coordinate

Any help is much appreciated.

**Comment by PolinaBevad** [comment]
Hi @qub-pete,

Thank you for using VarDict!
By default if there are few mutations on position VarDict will output only the mutation with the highest AF. 
Can you try to run `var2vcf_valid.pl`/`var2vcf_paired.pl` part with `-A` option and check if the mutation appears? This option allows to output all the good mutations (passing wuality checks) for the position.

Here is the description in perl script: https://github.com/AstraZeneca-NGS/VarDict/blob/master/var2vcf_valid.pl#L323

Hope it helps!

**Comment by qub-pete** [comment]
Hello @PolinaBevad 

I spoke with our bioinformatician and she has introduced the change you have recommended and the mutations are now being reported. Thank you for your quick response and the advice as it has really helped.

Kind regards,

Peter

**Comment by PolinaBevad** [comment]
Great, I'll close the issue then!
