### ISSUE TITLE
Running Vardict on large chromosomal chunks - May not be error

### ISSUE THREAD

**Issue by smboyle** [AstraZeneca-NGS/VarDict#15]
I would like to run Vardict on total RNA data, allowing for variants to be called anywhere they are observed along the chromosome.  I have tried breaking the chromosome into 6 segments (by bed) and running verdict on each segment.  I've found that verdict will run for many hours and will often return an empty variant file.  

My question is, can Vardict java be run on such large segments or is this issue expected?  If it is expected, what is your suggestion for running on total RNA data?

Thanks in advance!

**Comment by mjafin** [comment]
Hi @smboyle, sorry for the delay in addressing this. I presume your issue is related to https://github.com/AstraZeneca-NGS/VarDictJava/issues/33 and it got resolved? If not, let us know
