### ISSUE TITLE
vardict cannot call this insertion

### ISSUE THREAD

**Issue by cswph** [AstraZeneca-NGS/VarDict#159]
Hi,
I try to use vardict to call insertion at this this place ABXL:chr20:31022442. We used sample from seracare and it insert a 'G' at this position. I can also see there is insertion in IGV. Please see the attached picture.
<img width="455" alt="WeChatb89cea4b2e018995d1839e06e45b8892" src="https://user-images.githubusercontent.com/34529321/114411255-959be900-9bde-11eb-9dd0-f1da22d549d3.png">

But when I ran the vardict with these parameters,  -C -z -c 1 -S 2 -E 3 -g 4 -B 2 -v -f 0.005 -r 5 -m 8 -Q 60 -q 25 -X 10 -th 1 , it can only call the deletion, which much less than the insertion. So I tried different combination of the parameter settings and found that if I change the -q 10 I can successfully call it out. But when I check the base quality, the quality looks normal as the other bases. So could you help me to find out how it is filtered?

I also zip the bam file here.
[bam.zip](https://github.com/AstraZeneca-NGS/VarDict/files/6297501/bam.zip)

Thank you very much for the help!

**Comment by PolinaBevad** [comment]
Hi @cswph ,

It seems that both insertion and deletion must be on the same position, so did you try to run `var2vcf_valid.pl` step with `-A` option? By default we keep only the position with the highest AF.

**Comment by cswph** [comment]
Hi Polina,
Thanks for the reply! I think var2vcf_valid.pl is the step after the VarDict.  Out insertion is not even shown in the Vardict. And I try to use the simulated data, which include the insertion and deletion at this position, it can be called by Vardict. And the insertion has double amount of the deletion. 

Thanks again

**Comment by PolinaBevad** [comment]
That's strange, because I see this insertion even with standard options:
`vardict.pl -G human_g1k_v37_decoy.fasta -c 1 -S 2 -E 3 -g 4 -b RD2019242FFP.new.bam -R chr20:31022400-31022500`
it results in two variants on the position:
```
20      31022441        .       A       AG      204     PASS    SAMPLE=RD2019242FFP.new;TYPE=Insertion;DP=734;END=31022441;VD=52;AF=0.0708;BIAS=2:2;REFBIAS=356:221;VARBIAS=42:9;PMEAN=35.1;PSTD=1;QUAL=35.8;QSTD=1;SBF=0.00357;ODDRATIO=2.89276519424918;MQ=60;SN=104;HIAF=0.1161;ADJAF=0;SHIFT3=8;MSI=9;MSILEN=1;NM=0.4;HICNT=52;HICOV=448;LSEQ=GCGGCCACCACTGCCATCGG;RSEQ=GGGGGGGGTGGCCCGGGTGG;DUPRATE=0;SPLITREAD=0;SPANPAIR=0       GT:DP:VD:AD:AF:RD:ALD   0/1:734:52:577,52:0.0708:356,221:42,9
20      31022441        .       AG      A       158     PASS    SAMPLE=RD2019242FFP.new;TYPE=Deletion;DP=774;END=31022442;VD=21;AF=0.0271;BIAS=2:2;REFBIAS=433:318;VARBIAS=12:9;PMEAN=42.2;PSTD=1;QUAL=36;QSTD=0;SBF=1;ODDRATIO=1.02121;MQ=60;SN=42;HIAF=0.0282;ADJAF=0;SHIFT3=7;MSI=8;MSILEN=1;NM=0.5;HICNT=21;HICOV=745;LSEQ=GCGGCCACCACTGCCATCGG;RSEQ=GGGGGGGTGGCCCGGGTGGA;DUPRATE=0;SPLITREAD=0;SPANPAIR=0  GT:DP:VD:AD:AF:RD:ALD   0/1:774:21:751,21:0.0271:433,318:12,9
```
What version of VarDict do you use? I assume that you use Java program, as you set -th option (it works only in Java), please try to run with VarDict 1.7+
Options -v and -C are deprecated, so you can delete them from command line if you will use the new version.

**Comment by cswph** [comment]
OK, I will give it a try. Thank you!
