### ISSUE TITLE
Error Message when using VarDict

### ISSUE THREAD

**Issue by ttnpham** [AstraZeneca-NGS/VarDict#17]
Hi,

I ran VarDict on my bam files and it threw me this error:

```
Use of uninitialized value $sample in concatenation (.) or string at /home/ttnpham/vardict/VarDict-master/var2vcf_somatic.pl line 35.
Error: Incorrect input detected in teststrandbias.R
Execution halted
```

My bam files was aligned using BWA-MEM and was also local realigned and base quality recalibrated before it was input into VarDict.

The command I used is below

`
AF_THR=0.01
vardict -G ucsc.hg19.with_decoy.fasta -f $AF_THR -N case1_tumour -b case1_tumour.bam 
-c 1 -S 2 -E 3 -g 4 -Q 15 -q 15 TruSight_One_v1.1.bed | teststrandbias.R | 
var2vcf_valid.pl -N case1_tumour -E -f $AF_THR > case1_tumour.vcf`

**Comment by mjafin** [comment]
Hi @ttnpham, thanks for your interest in using VarDict and apologies for the error. To help us debug this a little bit can I ask you if your bam file is aligned against the fasta (`ucsc.hg19.with_decoy.fasta`) by yourself; in other words do the contig names between the bam and fasta agree? Further, do the contig names in the bed file agree with the contig names in the fasta/bam? 

Could you further paste a few lines frmo the bed file here to help debugging? Is it 3-column format or more?

**Comment by ttnpham** [comment]
My bed file was in the format of: 

> chr1    955541  955763  AGRN.chr1.955552.955753

I believe this is why it was throwing the problem, so I tried:

> chr1    955541  955763  AGRN

and it works fine. However, there is another problem
````
Error in .External2(C_writetable, x, file, nrow(x), p, rnames, sep, eol,  :
ignoring SIGPIPE signal
Calls: write.table
Execution halted

```
Which I cannot figure out :(

**Comment by mjafin** [comment]
@ttnpham that looks like a problem in R. What version of R are you using here?
You could break the call into separate lines like this:
```
vardict -G ucsc.hg19.with_decoy.fasta -f $AF_THR -N case1_tumour -b case1_tumour.bam -c 1 -S 2 -E 3 -g 4 -Q 15 -q 15 TruSight_One_v1.1.bed > 1.txt
cat 1.txt | teststrandbias.R > 2.txt
cat 2.txt | var2vcf_valid.pl -N case1_tumour -E -f $AF_THR > case1_tumour.vcf
```
and see if `1.txt` looks somehow funny

**Comment by ttnpham** [comment]
I am currently using R version 3.2.1 and yes I noted that there was an error outputted in R:
```
Error in scan(file, what, nmax, sep, dec, quote, skip, nlines, na.strings,  :
  line 55370 did not have 34 elements
Calls: read.table -> scan
Execution halted
Use of uninitialized value $sample in concatenation (.) or string at /home/ttnpham/vardict/VarDict-master/var2vcf_somatic.pl line 35.
```
I will try running your command and check why line 55370 does not have 34 column

**Comment by ttnpham** [comment]
For some season, on line 55370 there was an unwanted hidden character right after the gene name:
`case01_tumour_FE^IISCA_nsv491548^M^Ichr2^I243016301^I243016301^IC^IA^I155^I2^I82^I71^I1^I1^IC/A^I0.0129^I2;2^I39.5^I1^I31.0^I0^I60.0^I4.000^I0.0134^I0^I0^I2.000^I3^I1.0^I2^I149^IACACCCTGTTCTCATGAGGG^ITGCTTTAGGGGGAATTATTT^Ichr2:243016289-243016311^ISNV$`

**Comment by zhongwulai** [comment]
If you have BED files saved as text from Excel, remember to run dos2unix command before using it.  Otherwise, it might cause R to throw exceptions due to the carriage return character.  I'll build the removal in the script in the future.

**Comment by mjafin** [comment]
@ttnpham I'll close this issue - please reopen if Zhongwu's solution doesn't fit the bill
