### ISSUE TITLE
verdict on WGS tumor-normal pair

### ISSUE THREAD

**Issue by gnarzisi** [AstraZeneca-NGS/VarDict#18]
Is there any driver script to easily run vardict on a human WGS tumor-normal pair?

Due to memory requirements, it is not possible to run it on the whole genome. Even splitting by chromosome is not enough. Based on other posts, it is suggested to split the genome in 5kb overlapping regions of 150bp. However merging the downstream calls must be done carefully to consolidate the variants within the overlapping regions.

**Comment by zhongwulai** [comment]
The repository contains a bed file at 5kb segment with 150bp overlap for hg19.  The var2vcf* script will ensure that no duplicates are in vcf file.  The memory requirement is minimal for VarDict, so you can use 100-500kb segments to further reduce the overhead.

**Comment by gnarzisi** [comment]
Thank you for the quick replay Zhongwu.
It would be good to explicitly mention the hg19 BED file in the README.

**Comment by mjafin** [comment]
@gnarzisi thanks for your interest in VarDict. There are a few things that can help you further:
1. The first perl script can be replaced by a Java version that speeds things up (single thread) by around 10x, see https://github.com/AstraZeneca-NGS/VarDictJava. This is a drop-in replacement
2. If you don't want to parallelise manually, you could try running VarDict(Java) through bcbio, https://github.com/chapmanb/bcbio-nextgen, which automatically splits the regions and runs parallel processes via multiple supported schedulers. Bcbio also integrates Scalpel with MuTect SNP calls if you want to do a fair comparison. Bcbio further includes functionality to automatically compare variant calls to a gold standard, if you have a gold standard vcf available. @chapmanb has written up a comparison on several data sets where the ground truth is known, see http://bcb.io/2016/04/04/vardict-filtering/
