### ISSUE TITLE
only prints help

### ISSUE THREAD

**Issue by iiiir** [AstraZeneca-NGS/VarDict#23]
Hi, 
Needs some help as I always only gets help messages printed regardless what I tried.
example command:
vardict -G b37.fa -f 0.01 -N NA12878 -b NA12878.bam -c 3 -S 60132054 -E 60214549 ~/VarDict/my.bed

It immediately pops up helkp information indicating my command is mal-formated.
any help?
If we specify  -c 3 -S 60132054 -E 60214549 already, what is the bed file do?

I just couldn't find any more useful information regarding the parameters other than the printed help. and I amdo not read perl...

Thanks,
Shuoguo

**Comment by PolinaBevad** [comment]
@iiiir, sorry for the very late reply.
I will keep the answer here before closing the issue: -c, -S and -E options are the column numbers in BED file and not the coordinates of the region. So if BED file contains: 1 column - chromosome, 2 and 3 columns - start and end of the region, then option must be `-c 1 -S 2 -E 3`. The coordinates will be automatically obtained by VarDict from these columns.
