### ISSUE TITLE
AF, AD & DP values don't match!

### ISSUE THREAD

**Issue by jmfa** [AstraZeneca-NGS/VarDict#27]
Dear all,

I'm currently trying to use VarDict to call variants from a WXS experiment and I've noticed that most called variants have AD, AF and DP values that do not match. Here's one example:

`chr1    880745  .       A       G       47      PASS    .       GT:AD:ADJAF:AF:BIAS:DP:HIAF:MQ:NM:ODDRATIO:PMEAN:PSTD:QSTD:QUAL:RD:SBF:SN:VD    0/1:3,1:0:0.0132:2,2:302:0.0139:85.5:1:2.85:33.3:1:1:23.8:151,144:0.62316:8:4 ` 

As you can see, the AD is 3 and 1, AF is 0.0132 and DP is 302. I thought that AF estimates were obtained using the AD values for each allele. Do you have any idea why this is happening? 
Here's how I'm running the tool:

`
AF_THR="0.01"
VarDict -th 4 -GHg19.karyo.custom.fa \
        -f $AF_THR -N SAMP12 -b "SAMP12.bam|SAMP26.bam" \
        -c 1 -S 2 -E 3 -q 15 \
        -g 4 /home/cancer_ngs/2015.SANTIAGO/MuTect2.Calls/Targets.table.bed | testsomatic.R | var2vcf_somatic.pl \
        -N "SAMP12|SAMP26" -f $AF_THR > SAMP12.q15.VarDict.vcf
`

Thank you very much in advance!
Joao

**Comment by zhongwulai** [comment]
Please use var2vcf_paired.pl script to generate the VCF.  var2vcf_somatic.pl is deprecated, in which AD was defined as forward,reverse read count, not allele count.  You can find it in the VCF header.

Thanks!

**Comment by mjafin** [comment]
Cheers Zhongwu, will close the ticket.
