### ISSUE TITLE
Wrong genotype reported in VCF file

### ISSUE THREAD

**Issue by mdyckmanns** [AstraZeneca-NGS/VarDict#28]
In the var2vcf scripts, the frequency thresholds for the frequency filter and for the genotype get mixed when determining the genotype. The line should read
`my $gt = (1-$af < $GTFreq) ? "1/1" : ($af >= 0.5 ? "1/0" : ($af >= $GTFreq ? "0/1" : "0/0"));`
and similarly for `my $gtm = ...`.

In var2vcf_valid.pl, `s` and `o` are mixed up in the getopts line. It should read
`getopts('htaHSCEP:d:v:f:p:q:F:Q:o:N:m:I:c:r:O:X:k:V:M:') || Usage();`.

Thanks! Best, Malte

**Comment by mjafin** [comment]
@mdyckmanns thanks for the heads up. @zhongwulai could you confirm and @jabbarish apply a fix in Java too (once confirmed by Zhongwu)?

**Comment by PolinaBevad** [comment]
@mdyckmanns , thank you for pointing on this. Option `-o` was fixed, but genotype must be determined as it is, i.e the lower boundary is checked by frequency (i.e. `-f` option). Here it is in the documentation: https://github.com/AstraZeneca-NGS/VarDict/blob/master/var2vcf_paired.pl#L314
I will close this issue.
Thank you!
