### ISSUE TITLE
3 column bed file

### ISSUE THREAD

**Issue by kbthomas59** [AstraZeneca-NGS/VarDict#29]
Java VarDict gives an immediate java.lang.ArrayIndexOutOfBoundsException when I try a 3-column bed file. The bed file looks like (tab delimited)
chr1 65509 65625
chr1 65831 65973
chr1 69481 69600
chr1 721381 721519
chr1 721530 721806
...

Information from an individual line works with the -R option.
An 8-column bed file does work with columns 4,5 and 6 empty like
chr1 65509 65625    65509 65625
...

Does this suggest that "amplicon mode" is always on? I have tried the -z option and that hasn't changed this behavior.  Where have I gone wrong?

**Comment by PolinaBevad** [comment]
@kbthomas59, hello!
Sorry for the very late reply, but for keeping in history: 3 column BED now is supported by Java and Perl versions of VarDict. 
For the amplicon mode now we have the limitation: BED must contain exactly 8 columns with 7 and 8 columns containing the start and the end of amplicon.
