### ISSUE TITLE
Warning messages

### ISSUE THREAD

**Issue by lethalfang** [AstraZeneca-NGS/VarDict#3]
This is the command:
vardict -G human_g1k_v37_decoy.fasta -f 0.01 -h -b 'tumor.bam|normal.bam' -z -F -C -c 1 -S 2 -E 3 -g 4 11.per5000.bed > 11.var

I get messages such as this. I'm not sure what they mean.

Use of uninitialized value $ref in numeric eq (==) at /home/ltfang/apps/VarDict/vardict line 259.
Use of uninitialized value $ref in substr at /home/ltfang/apps/VarDict/vardict line 261.
Use of uninitialized value $var in substr at /home/ltfang/apps/VarDict/vardict line 261.
Use of uninitialized value $ref in numeric eq (==) at /home/ltfang/apps/VarDict/vardict line 263.
Use of uninitialized value $ref in numeric gt (>) at /home/ltfang/apps/VarDict/vardict line 265.
Use of uninitialized value in numeric lt (<) at /home/ltfang/apps/VarDict/vardict line 471.
Use of uninitialized value $ref in numeric eq (==) at /home/ltfang/apps/VarDict/vardict line 259.
Use of uninitialized value $ref in substr at /home/ltfang/apps/VarDict/vardict line 261.
Use of uninitialized value $var in substr at /home/ltfang/apps/VarDict/vardict line 261.
Use of uninitialized value $ref in numeric eq (==) at /home/ltfang/apps/VarDict/vardict line 263.
Use of uninitialized value $ref in numeric gt (>) at /home/ltfang/apps/VarDict/vardict line 265.
Use of uninitialized value in numeric lt (<) at /home/ltfang/apps/VarDict/vardict line 471.
Use of uninitialized value $ref in numeric eq (==) at /home/ltfang/apps/VarDict/vardict line 259.
Use of uninitialized value $ref in substr at /home/ltfang/apps/VarDict/vardict line 261.
Use of uninitialized value $var in substr at /home/ltfang/apps/VarDict/vardict line 261.
Use of uninitialized value $ref in numeric eq (==) at /home/ltfang/apps/VarDict/vardict line 263.
Use of uninitialized value $ref in numeric gt (>) at /home/ltfang/apps/VarDict/vardict line 265.
Use of uninitialized value in numeric lt (<) at /home/ltfang/apps/VarDict/vardict line 471.
Use of uninitialized value $ref in numeric eq (==) at /home/ltfang/apps/VarDict/vardict line 259.
Use of uninitialized value $ref in substr at /home/ltfang/apps/VarDict/vardict line 261.
Use of uninitialized value $var in substr at /home/ltfang/apps/VarDict/vardict line 261.
Use of uninitialized value $ref in numeric eq (==) at /home/ltfang/apps/VarDict/vardict line 263.
Use of uninitialized value $ref in numeric gt (>) at /home/ltfang/apps/VarDict/vardict line 265.
Use of uninitialized value in numeric lt (<) at /home/ltfang/apps/VarDict/vardict line 471.

Thanks.

**Comment by PolinaBevad** [comment]
This issue will be closed because it is outdate.
