### ISSUE TITLE
Calling structural variants

### ISSUE THREAD

**Issue by marizavo** [AstraZeneca-NGS/VarDict#30]
I have been using VarDict to call SNVs and INDELs, and I think it is a very good variant caller. I would also like to use it to call structural variants. What is the command line to do that? I know one would have to use the vardict_sv.pl script, but probably in combination with the main vardict call. Is that the case?

Thanks,
Maria Z

**Comment by mjafin** [comment]
@zhongwulai any comments?

**Comment by PolinaBevad** [comment]
@marizavo, hello!
This is an extremely late reply, but just to inform you: VarDict now support structural variants calling (DUP, INV, and DEL types) in both VarDictJava and Vardict Perl (in vardict.pl).
I will close this issue.
