### ISSUE TITLE
can not be run in background

### ISSUE THREAD

**Issue by lozybean** [AstraZeneca-NGS/VarDict#31]
When use vardict as a background command, such as
```
vardict -G /path/to/hg19.fa -f $AF_THR -N sample_name -b /path/to/my.bam -c 1 -S 2 -E 3 -g 4 /path/to/my.bed &
```
the above command will be done immediately, and no output, is there something wrong?

**Comment by mjafin** [comment]
Hi @lozybean, the output goes to stdout so you may want to redirect the output to a file using the chevron operator. You might want to use `nohup` with `&` if you plan on logging off the server while VarDict is calling variants.

Have you considered using bcbio (https://github.com/chapmanb/bcbio-nextgen) as it does all of parallelisation and vardict calling in one go?

**Comment by wangdongli** [comment]
my problem is the same to you. have you solved it already?

**Comment by mjafin** [comment]
Hi @wangdongli, as mentioned, the output by default goes to `stdout` so you have to pipe it to the follow up command (strand bias testing) or redirect to a file if you don't want it printed on screen.
