### ISSUE TITLE
no outcome

### ISSUE THREAD

**Issue by wangdongli** [AstraZeneca-NGS/VarDict#32]
hello,when I run the sample command ,there were no outcome file but print the usage.
what's the problem?
i'm looking forward to your reply

**Comment by mjafin** [comment]
Hi @wangdongli sorry may I ask you what the command is you were trying to run?

I would recommend running VarDict as part of bcbio, https://github.com/chapmanb/bcbio-nextgen, if you're not super comfortable with VarDict standalone.

**Comment by PolinaBevad** [comment]
@wangdongli, hello!
I will close the issue because it is outdated and many changes have been made to VarDict at the moment.
If you will try the new version and you will have any questions, feel free to ask them. Thank you!
