### ISSUE TITLE
Phasing issues with MNVs

### ISSUE THREAD

**Issue by jyen2** [AstraZeneca-NGS/VarDict#33]
Is phasing and MNV calling a known issue with Vardict? In my sample, a dinucleotide variant was missed by Vardict and called as two independent variants. The MNV was clear in the pileup.  Bizarrely, in subsequent dilutions of the same sample, Vardict was able to correctly identify and report the MNV. It also reported the two, adjacent variants. I wanted to point out this inconsistency and see if anyone else was getting this bug (b/c of phasing?) and if this issue is being addressed. 

Thanks,
Jenn

![image](https://cloud.githubusercontent.com/assets/24445163/20994041/dc124106-bca2-11e6-84f3-8093d1d7b39c.png)

**Comment by mjafin** [comment]
Hi @jyen2, thanks for raising this. You have fairly high depth and I was wondering how it looks like in the other reads - is the variant homozygously there throughout all the reads? I.e. how representative is the above view of the total stack?

@zhongwulai any ideas here?

**Comment by jyen2** [comment]
@mjafin thanks for the quick reply. Neither variant is homozygous throughout all the reads, although there is definitely an imbalance between the allele fraction of the two SNVS, which becomes less apparent in subsequent dilutions e.g. 
Undiluted sample: snv1 = 6%, snv2 = 24%; 
50% Dilution: snv1 = 2%, snv2 = 6%;
..where when snv1 is present it is always in cis w/ snv2, imbalance shown below:

[2-1.0-scroll.pdf](https://github.com/AstraZeneca-NGS/VarDict/files/640319/2-1.0-scroll.pdf)
[2-0.5.pdf](https://github.com/AstraZeneca-NGS/VarDict/files/640320/2-0.5.pdf)

Let me know if you need any further info ~ thanks!

**Comment by PolinaBevad** [comment]
@jyen2, hello!
Sorry for the late reply, but in last versions of VarDict there were changes about MNV detection and now in the similar cases I saw that MNV was found. So I suppose this issue can be closed. If you still have some questions about VarDict, please, let us know.
Thank you!
