### ISSUE TITLE
Reported genotypes 1/0 vs 0/1

### ISSUE THREAD

**Issue by gabeng** [AstraZeneca-NGS/VarDict#34]
I noticed that VarDict reports both 1/0 and 0/1 genotypes. What does that mean exactly? The VCF spec does not explicitly mention this notation (another blind spot).

**Comment by mjafin** [comment]
@zhongwulai any insight you can provide?

**Comment by chapmanb** [comment]
Those should be equivalent unless they're followed by phased genotypes. The alternative orderings are meant to allow phased variants. For instance:
```
chr1  100   1/0
chr1  105   0|1
```
identifies the two variants as phased on different haplotypes. If you had no phasing:
```
chr1  100   1/0
chr1  105   0/1
```
Then the first `1/0` could be swapped with `0/1` and this would just be an output idiosyncrasy, but is legal in terms of the specification.

**Comment by gabeng** [comment]
I am not accusing you of any illegal variant calling. This sounds like VarDict is capable of phased variant calling? (that would be awsome)
