### ISSUE TITLE
Somatic  variant detection error: Output empity

### ISSUE THREAD

**Issue by bioinfo-dirty-jobs** [AstraZeneca-NGS/VarDict#40]
Derar all,
I need to use the perl version of vardictc on my centos 5.5. I use this command:

` /illumina/software/PROG2/VarDict/vardict -G /illumina/software/database/database_2016/hg19_primary.fa -f 0.01  -N 415_tumor -b "/mnt/ALIGN/415/Coclean/415.sorted.dup.recal.cleaned.bam|/mnt/ALIGN/415/Coclean/416.sorted.dup.recal.cleaned.bam" -c 1 -S 2 -E 3 -g 4 /illumina/software/database/database_2016/TARGET/truseq-exome-targeted-regions-manifest-v1-2.bed| testsomatic.R |var2vcf_paired.pl -N "415_tumor|416_normal" -f 0.01`

Generate empty file wih only the header. No error for debug. Could you please help me?

**Comment by mjafin** [comment]
Hi @bioinfo-dirty-jobs, thanks for trying VarDict and sorry about the problems. I take it you're using the Perl version? What's the output of the first command in the pipe? Can you also paste a few lines from the bed file and a few reads from the bam file?

**Comment by bioinfo-dirty-jobs** [comment]
Of course!! thanks for you fast reply:

The perl version is this:



```
`exome-targeted-regions-manifest-v1-2.bed` 
chr1	12098	12258	CEX-chr1-12099-12258
chr1	12553	12721	CEX-chr1-12554-12721
chr1	13331	13701	CEX-chr1-13332-13701
chr1	30334	30503	CEX-chr1-30335-30503
chr1	35045	35544	CEX-chr1-35046-35544
chr1	35618	35778	`CEX-chr1-35619-35778`


this is the bam file
`B0P8DQ1:83:H5WKGBCXY:1:2202:16270:55243	147	chr1	10034	0	71M	=	10053	-52	CCCGACCCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTA	CC41=.<C;,//CC=,..CBDA@:BBD@BACBDAAACBCAB@BBDAA@BAC@A@AAC@A@AAB?@?>?@>?	MC:Z:79M	BD:Z:KNOPNKKPOKLNKPOKLNKPOKLNKPOJKMJONJKMJONJKMJONJKMJONJKMINMIKMJONKMPNPOLL	MD:Z:3T1A65	PG:Z:MarkDuplicates.1	RG:Z:416	BI:Z:NQSTSNNQSPPSNQSPPSNQSPPSNQRPORMPROORMPROORMPROORMPROORMPROORNQSPQTPQSPP	NM:i:2	MQ:i:0	AS:i:65	XS:i:67
B0P8DQ1:83:H5WKGBCXY:2:2205:15592:6460	97	chr1	10050	6	100M	chr9	10322	0AACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCAACCCTAACCCTAACCCGAACCCGAACCCGAACCCGAACCC	@@>??C>?BAACA?=@AC?ACABCAAA?@B@BCAACABCAACAB?>>5@BCA?@AABB@AB<?ACAAB@BCABB/B7BBBBB5B>;AB=CC?@B8<?@?@	XA:Z:chr10,-135524425,30M1D58M12S,2;chr21,-48119786,18S23M1D59M,2;chr4,-191043943,100M,6;	BD:Z:LLMOPQPNNPKMMLLNJLLKLNJLLKLNJLLKLNJLLKLNJLLKLNJLLKLNJLLKLNJOMMOKMMLMOKMMLMOKMQNMOKMRONPLNRPOQNPUNMOK	MD:Z:76T5T5T5T5PG:Z:MarkDuplicates.1	RG:Z:416	BI:Z:PPPRPTSOPQMRQNOPLQPNNPLRQNOQMRQNOQMRQNOQMRQNOQMRQNOQMRQNOQMSPPRNRROPRNSROPRNRUQQSOSVRQTPTXTSVRVZQPRN	NM:i:4	AS:i:80	XS:i:76
`
```
I will try to use on RHEL 5.5 also the java version and try the single begfore the paired..but again not gave me an output...
```
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
illumina/software/PROG2/VarDictJava-1.4.8/bin/VarDict -G /illumina/software/database/database_2016/hg19_primary.fa  -f 0.01  -N 415_tumor -b /mnt/ALIGN/415/Coclean/416.sorted.dup.recal.cleaned.bam -c 1 -S 2 -E 3 -g 4 /illumina/software/database/database_2016/TARGET/truseq-exome-targeted-regions-manifest-v1-2.bed |teststrandbias.R |var2vcf_valid.pl  -N 415_tumo -E -f 0

```

But

**Comment by mjafin** [comment]
So does running the first command in the pipe result in any output at all? If possible, limit the bed file regions to an exon where you know there should be variability

**Comment by bioinfo-dirty-jobs** [comment]
It still running but no rows in there.
This is exome data so this is the  bed file of the target regions.

**Comment by mjafin** [comment]
That probably explains the problems you're seeing. VarDict needs to be explicitly parallelised by splitting the regions. Running on a whole exome will probably make your process run out of memory (and will take a long time). 

Have you considered using an engine like bcbio (https://github.com/chapmanb/bcbio-nextgen/) to do all the parallelisation work for you?

Just for a simple test, try calling using a bed file with a small region where there are common (db)SNPs and you should be able to see some output.

**Comment by bioinfo-dirty-jobs** [comment]
If I use single  sample it works with only 10 rows on bed file. However I have this error:

` /illumina/software/PROG2/VarDictJava-1.4.8/bin/VarDict -G /database_2016/hg19_primary.fa  -f 0.01  -N 415_tumor -b /mnt/ALIGN/415/Coclean/416.sorted.dup.recal.cleaned.bam -c 1 -S 2 -E 3 -g 4 prova.bed |teststrandbias.R |var2vcf_valid.pl  -N 415_tumo -E -f 0.01 > 415_tumor_vardict.vcf 
Warning message:
closing unused connection 4 (myinput)`

Unfortunately there is many incompatibility on  RHEL 5.5 with the bbcio so I can't install without change destabilize the system.
What is the maximum of the  elements can manage for  core?
Thanks so much!

**Comment by mjafin** [comment]
The `-N` parameters don't seem to be identical between the first and third commands (`415_tumor` vs `415_tumo`) although I'm not sure this would lead to the error you're seeing. I've never seen that one before. You could try to trace the error by streaming all the individual steps into text files rather than piping and trying to see the cause that way. 

Regarding parallelisation, you probably want to split each chromosome into 5-10 parts and combine in the end. Depends on how much time you're willing to spend on this and how much RAM your servers have. I'll close the ticket now but feel free to ask any further questions. 

I forgot about the pains of running RHEL 5.x - our clusters are fully upgraded to RHEL 6 and 7, of which I'm ever grateful to our admins.
