### ISSUE TITLE
TruSeq Custom Amplicon bed file

### ISSUE THREAD

**Issue by rjsicko** [AstraZeneca-NGS/VarDict#44]
I'm interested in using VarDict with samples run using a TruSeq custom amplicon (TSCA) panel. I see amplicon aware mode using an 8 column bed file. The trouble I'm having is generating the necessary bed file from the provided design files. Has anyone used TSCA design files to generate the necessary bed file for vardict?
Thanks,
Bob

**amplicons.bed** 
````
chr9	340100	340375	chr9:340100:340375:116489980	275	+
chr9	340658	340888	chr9:340658:340888:116489981	230	+
chrX	100615078	100615353	chrX:100615078:100615353:116489982	275	+
chr11	108160167	108160398	chr11:108160167:108160398:116489983	231	+
````

targets.bed
````
chr10	14978536	14978592	chr10:14978536:14978592:DCLRE1C.FiveUtrExon.chr10.14978537.14978592:UserDefined	56	+
chr10	14987103	14987188	chr10:14987103:14987188:DCLRE1C.FiveUtrExon.chr10.14987104.14987188:UserDefined	85	+
chrX	100630131	100630302	chrX:100630131:100630302:BTK.FiveUtrExon.chrX.100630132.100630302:UserDefined	171	+
chr10	14984112	14984434	chr10:14984112:14984434:DCLRE1C.FiveUtrExon.chr10.14984113.14984434:UserDefined	322	+
chr10	14981808	14981868	chr10:14981808:14981868:DCLRE1C.FiveUtrExon.chr10.14981809.14981868:UserDefined	60	+
chr8	61653817	61655656	chr8:61653817:61655656:CHD7.FiveUtrExon.chr8.61653818.61655656:UserDefined	1839	+
````
**manifest file** 
![image](https://cloud.githubusercontent.com/assets/7218576/23225593/63e5dbc6-f900-11e6-88b6-73eb0658d66f.png)

**Comment by mjafin** [comment]
Hi @rjsicko, 
We haven't actually run TSCA panel samples internally as it isn't great with the degraded samples we typically deal with.

Amplicon mode in VarDict is designed for PCR amplicon panel data where there is some overlap between amplicons but not complete. The bed files we have the whole amplicon (with the primers) in columns 2-3 and the insert (without primers) in columns 7&8. If you can get the primer/probe locations for your panel you should be able to deduce what you need. I'm not sure if this information is captured in your screenshot though.

**Comment by rjsicko** [comment]
Hi Miika,
In our TSCA design we have ~50bp overlap (~250bp amplicon) on one or both ends of the amplicon. I do have amplicon coordinates, but I don't think I have insert size w/o primers. I do have the probe sequences from the manifest file so I could try to blast to get genomic coordinates. 

Thanks,
Bob

**Comment by mjafin** [comment]
Hi Bob,
Good luck with putting the bed file together, let us know how it goes.
