### ISSUE TITLE
Can't locate Stat/Basic.pm in @INC 

### ISSUE THREAD

**Issue by nashera** [AstraZeneca-NGS/VarDict#50]
When I run vardict2mut.pl, it told me that "Can't locate Stat/Basic.pm in @INC ".
But I can't find the module Stat::Basic in the cpan repository.
How can I install the module  Stat::Basic?

**Comment by mjafin** [comment]
@zhongwulai is Stat/Basic a private function?

**Comment by vladsaveliev** [comment]
`Stat::Basic` seems to be a custom library in a separate file. Since it's already published in Seq2C's repository, I guess it's okay to add it here too.

**Comment by vladsaveliev** [comment]
@nashera I added Stat/Basic into the source root, please update and retry.

Note that in `vardict2mut.pl` there are several hardcoded files containing data for prioritization, that cannot be published. So you'll see many warnings. The script should still be useful without them.

**Comment by zhongwulai** [comment]
@vladsaveliev Thank you Vlad.  Yes, Stat::Basic is a custom perl module I wrote and published in Seq2C.
