### ISSUE TITLE
Mislabeling as AMPBIAS

### ISSUE THREAD

**Issue by timothee-revil** [AstraZeneca-NGS/VarDict#52]
Hi,

VarDict is mislabeling a SNV as being AMPBIAS for 2 of my three samples. As you can see in the picture, there are multiple overlapping amplicons that contain the SNV.

![igv_snapshot](https://user-images.githubusercontent.com/8106106/31558083-7d8095fa-b019-11e7-9552-c59b3edf7a1b.png)

Any idea what could be causing this issue?

Thanks,
Tim

**Comment by mjafin** [comment]
Hi Tim,
Sorry about the issue you're seeing. Ampbias is triggered when running VarDict in amplicon-aware mode when, out of multiple overlapping different amplicons, only one supports the variant. 

What does your bed file look like in this exact region? How many amplicons are there?

**Comment by timothee-revil** [comment]
Hi Mika,

There are 5 amplicons overlapping this particular variant, 4 of which pick it up (it is in the middle of the fifth, so not sequenced).

![igv_snapshot](https://user-images.githubusercontent.com/8106106/31619922-e2fc03b4-b263-11e7-82fe-e4ec7149fe7c.png)

**Comment by mjafin** [comment]
Sorry this dropped off my radar. If I remember correctly there is a rule in VarDict that says all amplicons must support a variant for it to be called. I'd ask @zhongwulai but not sure if he's monitoring this ticket.

**Comment by PolinaBevad** [comment]
Hi Tim!
Sorry for the very late reply! 
I want to confirm the last comment from Miika, that flag will not be triggered only if all amplicons support the variant. Because one amplicon doesn't support it, AMPBIAS flag was set in this case.
I will close this issue. Let me know if there are any other questions.
