### ISSUE TITLE
how to call CNV  in amplicon mode?

### ISSUE THREAD

**Issue by Tinalxt** [AstraZeneca-NGS/VarDict#53]
Hi~I run the Vardict to call CNV with the 8-col bed file using the runVarDict_BAM.sh. I wonder if I call CNV in the right way?

**Comment by mjafin** [comment]
Hi @Tinalxt, thanks for the interest in VarDict. VarDict isn't a copy number caller but you can use it for SNVs and InDels. The 8-col bed file format should only be used when calling variants in PCR amplicon panel data where the amplicons and inserts are described with help of the extra columns.

**Comment by PolinaBevad** [comment]
@Tinalxt, hello!
This issue will be closed because the reply was given. 
For CNV you can also use Seq2C variant caller, it supports amplicon mode: https://github.com/AstraZeneca-NGS/Seq2C
