### ISSUE TITLE
Deletion with AF>1

### ISSUE THREAD

**Issue by vladsaveliev** [AstraZeneca-NGS/VarDict#54]
Ran into a variant with DP=7; VD=8: 
```
20      62919376        .       TAAG    T       111     PASS    
TYPE=Deletion;DP=7;VD=8;AF=1.1429;BIAS=0:0;REFBIAS=0:0;VARBIAS=8:0;PMEAN=31.3;
PSTD=1;QUAL=37;QSTD=1;SBF=1;ODDRATIO=0;MQ=21.3;SN=16;HIAF=1;ADJAF=0.1429;
SHIFT3=0;MSI=3;MSILEN=3;NM=1.1;HICNT=8;HICOV=8;LSEQ=TAATTTTTAATTGAGTGGAA;
RSEQ=AATAATATTGATAAAAGTAG;dgv=CopyNumber 
GT:DP:VD:AD:AF:RD:ALD   1/1:7:8:0,8:1.1429:0,0:8,0
```

Did anyone see such things before? Is there a realistic reason it can happen, or it's a bug? Trying to avoid digging into perl.

**Comment by lubinskibu** [comment]
AF is greater than 1… so I’m leaning towards bug… sometimes I’ve seen different depth callers report differing depths, or perhaps the region of the deletion is being counted? But definitely something strange there.

Tristan J. Lubinski Ph.D.
Associate Scientist
NGS Informatics
AstraZeneca

**Comment by lubinskibu** [comment]
Maybe spoke too soon, it looks like AF is greater than 1 when we have inserts as well, so maybe it’s not entirely unexpected.

Tristan J. Lubinski Ph.D.
Associate Scientist
NGS Informatics
AstraZeneca

From: Lubinski, Tristan
Sent: Wednesday, November 08, 2017 8:58 AM
To: 'AstraZeneca-NGS/VarDict' <reply@reply.github.com>; AstraZeneca-NGS/VarDict <VarDict@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Subject: RE: [AstraZeneca-NGS/VarDict] Deletion with AF>1 (#54)

AF is greater than 1… so I’m leaning towards bug… sometimes I’ve seen different depth callers report differing depths, or perhaps the region of the deletion is being counted? But definitely something strange there.

Tristan J. Lubinski Ph.D.
Associate Scientist
NGS Informatics
AstraZeneca

**Comment by PolinaBevad** [comment]
It seems @lubinskibu is right, this is not entirely unexpected.
AF >1 could take place in indels case. A field ADJAF contains extra frequency for indels (AF=1.1429, ADJAF=0.1429). Adjusting ADJAF from AF is a frequency without indels considering, which should not be greater then 1.

**Comment by vladsaveliev** [comment]
Thank you for replies, that makes sense for me now! Closing the issue.
