### ISSUE TITLE
Complex variants clarification

### ISSUE THREAD

**Issue by iranmdl** [AstraZeneca-NGS/VarDict#57]
Hello,
I'm missing something with the `Complex` variants, what is exactly the change for the following variant? The only thing I'm sure is that the reference C in position 58017753 changes to an A, but then.. I get lost with the notation.

`19	58017753	.	CAGCTG	AGAGGCTC	188	PASS	LSEQ=GCAAGGAGCCAAGGCTGAGG;MSI=3.000;MSILEN=1;RSEQ=CTGAGCAGAGTGCTTCTGTA;SAMPLE=mut;SHIFT3=0;SOR=Inf;SSF=0;STATUS=StrongSomatic;TYPE=Complex	GT:AD:ADJAF:AF:ALD:BIAS:DP:HIAF:MQ:NM:ODDRATIO:PMEAN:PSTD:QSTD:QUAL:RD:SBF:SN:VD	0/0:81,0:0:0:0,0:2,0:128:0.648:60:0.1:0:15.4:1:1:36.7:27,54:1:162:0	0/1:72,39:0.0708:0.3451:18,21:2,2:113:0.3451:60:0.1:1.94:24.5:1:1:35.6:22,50:0.14667:78:39
`

Another question is, is it possible to convert `complex` variants to individual simple changes? Separate rows with SNPs and the indels that define the complex variation.

Thank you in advance,

**Comment by chapmanb** [comment]
Thanks for the question, these complex variants represent multiple phased events and the best way to think about them is to translate the sequences into an alignment. In this case it looks like a deletion, insertion and SNP:
```
CAG---CTG 
-AGAGGCTC
```
If you're like to have these normalized to separate events you could use bcftools norm (http://www.htslib.org/doc/bcftools.html#norm):
```
bcftools norm -m '-both' -O z -o out.vcf.gz in.vcf.gz
```
Hope this helps.

**Comment by iranmdl** [comment]
Thanks for the help :)
May I ask you to elaborate how do you know that the change is that specific change?:
```
CAG---CTG 
-AGAGGCTC
```
How can you interpret that from this variant `CAGCTG` --> `AGAGGCTC` in the vcf file? So we have the first C deleted, the following 2 bp are kept, then AGG insertion, then CT kept, and finally a SNP from G to C. I have several other occurrences of complex variants in my VCF file and I would like to interpret these lines by myself :).

**Comment by chapmanb** [comment]
I'd suggest using the bcftools norm command listed above to resolve these for your other cases. Depending on the complexity there are often multiple ways you can resolve them, and none is any more correct than another. My goal in making the above alignment by hand was to limit the number of events and most of the automated approach also take this parsimony approach so will do this as well. In the end the real event is the bigger change that VarDict lists by default but the automated tools help make the job of resolving to discrete events easier. Hope this helps.
