### ISSUE TITLE
ROC generation

### ISSUE THREAD

**Issue by sangtaekim** [AstraZeneca-NGS/VarDict#60]
I successfully ran VarDict using bcbio-nextgen for the ICGC medulloblastoma dataset. I'd like to create an ROC curve to compare it with other tools. Is there a single score that controls recall/precision trade-off? I've tried SOR, SSF, and QUAL, but none of these produced a pretty ROC curve.

**Comment by mjafin** [comment]
Hi @sangtaekim,
Great to hear that. Have you tried something as simple as allelic fraction or variant depth? Or one of those multiplied by QUAL? It's difficult to filter variants out based on these data metrics purely but Brad Chapman did some work on this some time ago, see http://bcb.io/2016/04/04/vardict-filtering/

**Comment by sangtaekim** [comment]
Thanks @mjafin! I'll check whether this filter is implemented in the bcbio-nextgen VarDict pipeline.

**Comment by PolinaBevad** [comment]
@sangtaekim, hello!
I will close this issue because some recommendations were given but feel free to ask any questions about VarDict.
