### ISSUE TITLE
Regression conforming to the VCF spec

### ISSUE THREAD

**Issue by nh13** [AstraZeneca-NGS/VarDict#62]
See [commit and comment](https://github.com/AstraZeneca-NGS/VarDict/commit/38e85e9854bcdcb631de35321e852ff7ce3b01c0#r28908148).  It looks like we need a unit test to ensure that ALT="." and GT=0/0 when no variant is present.  @zhongwulai commits like this make it hard to rely upon VarDict, as extremely useful features are removed at the drop of a hat and there's no way to know when and why.

**Comment by mjafin** [comment]
I suspect @zhongwulai you had not pulled the latest updates from Github before committing yours?

**Comment by zhongwulai** [comment]
@nh13 My apology!  Forgot to sync first.  We'll make changes ASAP.

**Comment by nh13** [comment]
@zhongwulai thanks, this was certainly disconcerting, but I appreciate that it was an unintentional mistake and appreciate that you will revert.

**Comment by zhongwulai** [comment]
@nh13 It's now updated.  Please let us know if there're still problems.  Thanks!
