### ISSUE TITLE
How can I filter variants with 0 or low read in normal sample for paired analysis?

### ISSUE THREAD

**Issue by SaHash** [AstraZeneca-NGS/VarDict#65]
Hello. I'm sorry if it is a trivial question.
When I performed paired analysis, there were so many variants comparing other analysis softwear because most of the variants were 0 or very low read in normal sample.
How can I filter those and keep variants with high quality present in both samples ?
I use MacOS X 10.13.1, VarScan ver1.5.1, Java ver1.8.0_144, R ver3.4.4, perl ver5.18.2
The comand is like this;

$ AF_THR="0.01"

$ /Users/sh/VarDictJava/VarDict-1.5.1/bin/VarDict -G /Users/sh/ucsc.hg19.fasta -f $AF_THR -N tumor -b "/Users/sh/tumor.bam|/Users/sh/normal.bam" -z 1 -c 1 -S 2 -E 3 -g 4 /Users/sh/ucsc.hg19.bed | /Users/sh/VarDictJava/VarDict/testsomatic.R | /Users/sh/VarDictJava/VarDict/var2vcf_paired.pl -N "tumor|normal" -f $AF_THR > X.vcf

Thanks in advance.

**Comment by chapmanb** [comment]
I'd suggest filtering the output VCF using bcftools. It's pretty flexible and can soft filter variants by a lot of criteria (http://www.htslib.org/doc/bcftools.html#filter). For your example, to filter anything with less than 2 reads in the normal (second) sample:
```
bcftools filter -s LowNormal -e 'FORMAT/DP[1] < 2' X.vcf
```
Hope this helps.

**Comment by SaHash** [comment]
Thanks @chapmanb! 
I'll try to use bcftools.
