### ISSUE TITLE
What does the QUAL column in vcf mean?

### ISSUE THREAD

**Issue by pinetree1** [AstraZeneca-NGS/VarDict#67]
Is the QUAL column (not the QUAL in the INFO fields) in vcf generated by vardict the phred-adjusted score as in vcf specification? How is it calculated by vardict? Is it going to change based on the number of ploidy.

**Comment by annaquaglieri16** [comment]
Hi @mjafin , I was wondering the same thing. Sometimes the QUAL are the same, sometimes slightly different and some other times very different. Is the QUAL in the INFO field a sort of average?

Thanks, 

Anna

**Comment by mjafin** [comment]
@zhongwulai @pcingola I wonder if you can shed some light on this one?

**Comment by PolinaBevad** [comment]
@pinetree1, @annaquaglieri16, hello!
This is a late reply, but I can explain how QUAL column and field and INFO are calculated: 
The initial qual in INFO field is simply the average base quality from the reads covers the variant. 
To calculate QUAL column field, we use log2 normalization of the initial qual with variant depth like: `qual*log(VD)/log(2)`. 
I will close the issue, but if you will have additional questions, please re-open it or create a new one.

**Comment by arolni** [comment]
Hi @PolinaBevad,

Based on your explanation (QUAL = qual*log(VD)/log(2)), does that mean that the QUAL column is not phred-quality score? How would one do a post-variant calling filtering when using Vardict then? Normally QUAL > 20 is used, but I find that there are many false-positive variants with high QUAL scores, and it seems like it is calculating a different thing from other callers. Thanks!
