### ISSUE TITLE
Make 'AD' field in VCF header Number=R

### ISSUE THREAD

**Issue by TMiguelT** [AstraZeneca-NGS/VarDict#75]
In the script that converts the VarDict output to a VCF, it adds a header for the `AD` field that has `Number=.`:

https://github.com/AstraZeneca-NGS/VarDict/blob/12e24ad1fcd6e18c93a55a0bcbc61fe1a9d31ca2/var2vcf_valid.pl#L94

For the reasons explained [here](https://gatkforums.broadinstitute.org/gatk/discussion/6919/change-format-of-ad-field-to-number-r), this field should have `Number=R`, since it has one value for each allele (including reference). This change will assist downstream tools especially.

I'm using VarDictJava, but I gather that it uses the same script so everyone would benefit from this fix.

**Comment by clintval** [comment]
I'm 👍 on this. Was about to submit a PR this evening!

**Comment by clintval** [comment]
I pinged the PR with docs support. I'm with you.

**Comment by chapmanb** [comment]
Thanks again for this, it's now merged and included and hopefully makes everyone's life easier dealing with VarDict outputs downstream. Much appreciated.

**Comment by clintval** [comment]
Thanks! We appreciate you too!
