### ISSUE TITLE
MNV's not called because they are not Phased

### ISSUE THREAD

**Issue by mezewudo** [AstraZeneca-NGS/VarDict#77]
Please, has anyone dealt with this scenario below regarding multi nucleotide polymorphisms, if the mutations are adjacent to each other, they are accurately called as MNVs, but if the mutations are separated by one nucleotide base, Vardict interprets them as single independent mutation events: see POS 4055964 and 4055962 in the attached VCF file, should have been merged into one multi-nucleotide variant, and not 2 separate SNPs.

[test_annotation.txt](https://github.com/AstraZeneca-NGS/VarDict/files/2267673/test_annotation.txt)

**Comment by ahwanpandey** [comment]
Hey there,

This might not answer your question directly but GATK has a standalone tool to phase SNPs into MNPs that you might try post-variant calling. The options [--maxGenomicDistanceForMNP] and [--enableMergePhasedSegregatingPolymorphismsToMNP] would be of relevance to you.

https://software.broadinstitute.org/gatk/documentation/tooldocs/3.8-0/org_broadinstitute_gatk_tools_walkers_phasing_ReadBackedPhasing.php

Best.

**Comment by zhongwulai** [comment]
@mezewudo The feature has been added to the new version.  Now MNV allows 2bp matches in between by default.  This can be changed using -X option.  2bp was chosen as it would be within 1 condon length.
