### ISSUE TITLE
Incorrect number of columns for the output

### ISSUE THREAD

**Issue by gingerbuffy** [AstraZeneca-NGS/VarDict#78]
Hi,

I've just downloaded the software yesterday and run vardict with the following command
vardict -G rice.fa -f 0.01 -N A1 -b A1.bam -c 1 -S 2 -E 3 -g 4 rice_probe.bed > vardict_out.txt 
and the output I got has 36 columns instead of 34. The 35th and 36th column is always 0 0. An example of my output is
A1      gene1101   1       620344  620344  C       T       5       5       0       0       3       2       T/T     1.0000  0;2     21.61       38.4    1       28.0    10.000  1.0000  0       0       2.000   1       2.4     5       5       TAGTACTTGATCAGTGTTGT    CGTTTGATCTAGCAGTTGTT        1:620255-622554 SNV     0       0
A1      gene1101   1       620771  620771  T       C       3       3       0       0       0       3       C/C     1.0000  0;0     26.31       40.0    1       60.0    6.000   1.0000  0       1       1.000   1       4.3     3       3       TCGTTAAATCCTGAAAAATT    GAGTCCAACCTAAGACTTAA        1:620255-622554 SNV     0       0
A1      gene1 101  1       620744  620744  C       T       3       3       0       0       0       3       T/T     1.0000  0;0     39.71       35.7    1       60.0    6.000   1.0000  0       2       1.000   1       4.3     3       3       TACATCGTCTACCACTGAAG    ATAAAGTCGTTAAATCCTGA        1:620255-622554 SNV     0       0

Then I've tried VarDictJava on another machine with another dataset. I still get 36 columns. 
Both dataset was run using bwa mem.
What have I done wrong? Please help me.

Thank you

**Comment by geocarvalho** [comment]
Hello @gingerbuffy, I had the same issue using `vardict` from conda (`2017.09.24`). So I changed my code to use `vardict-java` (`1.4.10`) from conda and it created 34 columns normally.

**Comment by gingerbuffy** [comment]
Thank you very much @geocarvalho. I have one question. Are the first 34 columns exactly the same between the two version?

**Comment by geocarvalho** [comment]
@gingerbuffy exactly the same, my problem was the last two `0  0` as you noticed on your data.

**Comment by gingerbuffy** [comment]
@geocarvalho Thank you very much :)

**Comment by atomiuk** [comment]
I experienced the same issue.
You could change the following line in teststrandbias.R 
if (mynumcols == 34 || mynumcols == 38){ # 34 columns for standard bed files, 38 for amplicon mode
into
if (mynumcols == 36 || mynumcols == 38){ # 34 columns for standard bed files, 38 for amplicon mode
to get rid of this issue

**Comment by PolinaBevad** [comment]
@gingerbuffy, thank you for reporting issue! 
This error was fixed in last version - thanks for @atomiuk, that was exactly what we have to add. 
@geocarvalho
