### ISSUE TITLE
Unmapped reads: Skip as default

### ISSUE THREAD

**Issue by pcingola** [AstraZeneca-NGS/VarDict#81]
From SAM spec: https://samtools.github.io/hts-specs/SAMv1.pdf

Bit 0x4 is the only reliable place to tell whether the read is unmapped. If 0x4 is set, no assumptions
can be made about RNAME, POS, CIGAR, MAPQ, and bits 0x2, 0x100, and 0x800.

Change Line 106 should be 0x504 instead of 0x500

**Comment by zhongwulai** [comment]
It's now changed to 0x504.
