### ISSUE TITLE
String out of boundaries in CIGAR

### ISSUE THREAD

**Issue by pcingola** [AstraZeneca-NGS/VarDict#82]
The issue with StringOutOfBoundException in VarDictJava is also reproduced in Perl, but without crashing (because Perl works differently with negative indexes in the string). 

https://github.com/AstraZeneca-NGS/VarDictJava/pull/126  

VarDict Perl examples: Lines 1097, 1100
Correctly checked in other lines, e.g. line 1147

**Comment by PolinaBevad** [comment]
The PR was merged. I'll close the issue.
