### ISSUE TITLE
vardic from conda errror

### ISSUE THREAD

**Issue by bioinfo-dirty-jobs** [AstraZeneca-NGS/VarDict#99]
Dear all, I try to use the last version of vardict on bioconda. I don't found any R tools 
```
testsomatic.R 
testsomatic.R: command not found

```
It is normal?

**Comment by PolinaBevad** [comment]
@bioinfo-dirty-jobs, hello!
For the last version of VarDict this file must be in `vardict-2018.10.18-1/share/` folder of your conda installation folder. I tried to install it through miniconda and it is here. Also the links for it are in `bin` folder of conda. Could you please check this folder? 
Please be sure that you run this script after vardict step and R is installed on your system. `testsomatic.R` waits for the raw data from vardict to process it.

**Comment by PolinaBevad** [comment]
@bioinfo-dirty-jobs, hello!
Because there was no answer from you on the last message, I will close the issue. But you can reopen the issue if the problem still occurs.
Thank you!
